sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
    - libpq-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
- wget -O rambler https://github.com/elwinar/rambler/releases/download/4.2.0/rambler-linux-amd64
  && chmod +x rambler
- pip install --user awscli
before_script:
- aws s3 cp s3://ladder-billiards-test-config-us-east-1/rambler.json .
- "./scripts/dbinit"
- "./rambler apply"
script:
- stack --no-terminal test --haddock --no-haddock-deps
after_script:
- "./rambler reverse -a"
env:
  global:
  - secure: WEgHCLaawkIud1GRMJ8hk74z6uKpC6sHE7PQ1i1QTEwjtkay+rSDmxrdczRCkPB4AKCKLd9rvdWx5DCSPGxD9ekD5ZnW0TQmN0Do1hP+0IEDNSpyU1nyqg1KCm2AHWChj1rNnIIRNgBuYoo2REMJKGzMMpWuGXO101IZG8ihikcxFCy2WXxpAHZog1sBFP9o6iTgC4ywk/PaH8zHsorZoIMZDw3J0n4ppyUTs2e4jNsbMtz5xbMsp5hcpOVR69oaPBe7LgYg73T7Dn3puT8srQk5UJXEFAzMfpeD3sapHEL4mOykg82Yxr6GGoW0Ba/jnWoA+X3Tamg5skQpKkMxkBuZ5Q9pftFKJt6Lopg/5ydqKodI9TOLmChCE8x180UTESijVYoSuuu10b2pXmTOPp1f8mau39LQ4W8RwxsHkvKTBpvpnwHVtJbegWhe4sKuG8O5hzs61xqESvruXM5Fon+Apr/oVJeSxFKjuQUbetTOPBV36w1wA/EnIm80UtwjqhVAKFPrKzrtRB4/Ar4PiznMic2hkyaYJO7rqmdkBftOay3Kt7PouvhGtfNHn2P/8JiOspm+Voob8h8QzJOuUbCk1XocerjVaSjjuR0nH64Z00S+yqmoXBDcqbXCx0PTYo3SXsm62dSJOgVsz/pwZ7QAEGHKcxFxT0mu+qx8NYI=
  - secure: cObSrI6X6dTXWgVb/tK/UT5abBbM14qpPifej4BX9f+CMHzQDJV8wyFzEZ2UxonjNWfTZw7aFhycT3abaEnsAM58Ic/GgaZgFqIY2955FKGuKwcM9ATAc3IE4sgDhpmd52glgpY2rkS/bKpSegN+XH7/fWy5HSmC4HL05PG5ito/Aa743e+d9rOdu4PYES5GyA+e9IkRgp+4GKkm8ta6rqrug3wJRNquaR0d/goqz5FcPdOX+y7Z0YDUN/lc2lVeF7/jNE4IUQ0Jl/jbport4oy7Y36++SVVOUUxF8w4nASWFBfiATmyKT2acYU8Q7TsrEb5B34mzdzvMK8uNiw78s8TF8g+EQNIGZhbI0Cr0/UkpFt/bJvCmkHzGte6lNlWgxHgybE8EQJ8tzRziiIdEVBxDO4StCjkL7GYc1DR8gy6w63jFIxUoQy86afFvJGUSBmDRbIsCpDGQRJhqy8KvzlerLNu/WCuSaF+rT0SQidQrkFRvOSO789rVAlvdwJhG9L7ntIijymon3txInBAJ7s0BGavtr6MKjD+T3fulG4oKQ61fAtXI+N/lCfMJYDSaMZAD+xnij889LmXMLLOr0jtSSh7haxpaBHCpNLvCOpbT+nAeC1upwd7nSqKP5KlgSaWN41Gk8Cjn3dBVtUfdtPMBITJPV8MCi/SrONMphc=
  - secure: YkJPF1WPhf2KSVt8ieKviS3JCdRQwvd1VO43IWjZ9dMheCt0Ri2R/x8VIUpKRxsedPjGWMiGsiNrM0QEG1EvqTUZ3MaUa4tr7gGZWwnv1DDqd6sBJLLZrFDfQl8Lk/M1y8kJk/zitp3ypaDyPkhrv0HgL5orANrNJiXqVk7aqTcHizfAviCO5dbf8nZ17xEJ+GFpcsiI+w31q0aI4srFHRfYKNdgUeyDfqobUC7nwpFT2CxCJMH33GYJGXrfHhbh08/JEsULYQhPJSwySjTKxHsMHUuAdaiU/BPqkx7n5rEAivE/03lOHSWX99Q4YbzK6MiBh3fKuK8CZBWMIJT2I/d9fAHfSNzmrqZj0ZyokOKNqMi6+b/ST0aw4MklQdkDnhCu1B3CB6/2uJ/VoljU4TXhxBaAiFMnObgT2lEjUMr7McEUWF6Cocq9zkoOjO/y04tntXmylhI6jCm5CIuAdiviSdclKGiQUijKPDHn9Dr48ePSqwVz1hcNAd3VGoUVeUqqSsnAAhu4naqb5OpkxJVIL/ubdA+S4aGC8w3FT6QFMnJjCQmjJpoONQBp7DWm1hXJzSx3ZH3NSLiUmqcxPuJMSQTbQHSWYGc2kngZ7xs0jssZYMMexdStmmH3DpyPwfhxihs8efJm8q2OgQfGAigsN765wybCNwyjQI/Uvew=
