sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
    - libpq-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
- wget -O rambler https://github.com/elwinar/rambler/releases/download/4.2.0/rambler-linux-amd64
  && chmod +x rambler
- pip install --user awscli
before_script:
- aws s3 cp s3://ladder-billiards-test-config-us-east-1/rambler.json .
- "./scripts/dbinit"
- "./rambler apply"
script:
- stack --no-terminal test --haddock --no-haddock-deps
after_script:
- "./rambler reverse -a"
