#!/bin/bash

set -e

function usage() {
  echo -n \
       "Usage: $(basename "$0")

Initiailize the database with the correct db name and user
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        if [ "${1:-}" = "--test" ]
        then
            psql -c "create database ladder_test;" -U postgres || true
            psql -c "create user ladder password 'ladder';" -U postgres || true
    else
        postgres_db=${POSTGRES_DATABASE:-ladder}
        postgres_user=${POSTGRES_USER:-ladder}
        postgres_password=${POSTGRES_PASSWORD:-ladder}
        postgres_port=${POSTGRES_PORT:-5432}
        postgres_host=${POSTGRES_HOST:-localhost}
        dbCmd="create database $postgres_db;"
        userCmd="create user $postgres_user password '$postgres_password';"
        psql -c "$dbCmd" -U postgres -p "$postgres_port" -h "$postgres_host" || true
        psql -c "$userCmd" -U postgres -p "$postgres_port" -h "$postgres_host" || true
        fi
    fi
fi

