#!/bin/bash

function usage() {
  echo -n \
       "Usage: $(basename "$0")

Run tests
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        export PATH="$(pwd)":"$PATH"
        rambler -c rambler.json.test apply -a
        # test result stored instead of set -e for error-handling "finally"-like execution
        stack --no-terminal test --haddock --no-haddock-deps
        testResult="$?"
        rambler -c rambler.json.test reverse -a
        exit "$testResult"
    fi
fi
