#!/bin/bash

set -e

function usage() {
  echo -n \
       "Usage: $(basename "$0")

Run tests
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        rambler -c rambler.json.test apply
        stack --no-terminal test --haddock --no-haddock-deps
        rambler -c rambler.json.test reverse -a
    fi
fi